# ========================================================================================
# gen_xadc_ip.tcl - generates the xadc_wiz IP core for the 
# bucket-detector analog front end.
#
# Run once (or whenever the config below changes):
#   & "C:\Xilinx\Vivado\2024.2\bin\vivado.bat" -mode batch -source scripts/gen_xadc_ip.tcl
#
# Output lands in ip/xadc_wiz_0/xadc_wiz_0.xci - check that
# .xci into git; it's the reproducible source of truth. 
# The generated .v/.dcp build products stay out of git (gitignored),
# regenerated by build.tcl on each build.
# ========================================================================================

set PART "xc7a200tsbg484-1"
set IP_DIR "ip"

file mkdir $IP_DIR

create_project -in_memory -part $PART

create_ip -vlnv xilinx.com:ip:xadc_wiz:3.3 -module_name xadc_wiz_0 -dir $IP_DIR

set_property -dict {
    CONFIG.INTERFACE_SELECTION              {ENABLE_DRP}
    CONFIG.TIMING_MODE                      {Continuous}
    CONFIG.SEQUENCER_MODE                   {Continuous}
    CONFIG.XADC_STARUP_SELECTION            {channel_sequencer}
    CONFIG.ENABLE_CALIBRATION_AVERAGING     {false}
    CONFIG.ADC_CONVERSION_RATE              {1000}
    CONFIG.DCLK_FREQUENCY                   {100}
    CONFIG.CHANNEL_AVERAGING                {None}
    CONFIG.BIPOLAR_OPERATION                {false}
    CONFIG.CHANNEL_ENABLE_VAUXP0_VAUXN0     {true}
} [get_ips xadc_wiz_0]

generate_target all [get_ips xadc_wiz_0]

puts "XADC IP generated: $IP_DIR/xadc_wiz_0/xadc_wiz_0.xci"
