`timescale 1ns/1ps
`default_nettype none

// xadc_interface: continuous single-channel readout on top of the xadc_wiz_0
// IP (Xilinx XADC hard macro wrapper, generated by scripts/gen_xadc_ip.tcl).
//
// Drives the IP's DRP bus in free-run mode: eoc_out is looped straight back
// into den_in, so the moment one conversion finishes its result is read out
// and the next conversion starts immediately. daddr_in is held constant at
// VAUX0's DRP address (7'h10) since only one channel is enabled in the IP
// config (see ip/xadc_wiz_0/xadc_wiz_0.xci) -- no channel-cycling needed.
//
// do_out is 16 bits wide but only the top 12 (do_out[15:4]) are the real
// ADC reading; do_out[3:0] is padding. sample_valid pulses for one cycle
// whenever a fresh reading has just been latched into sample, so a consumer
// (e.g. correlator.sv's acc_we) can tell a new value apart from a stale one.
//
// reset_in on the XADC IP is active-high (fixed by the primitive, see
// xadc_wiz_0.xci POLARITY=ACTIVE_HIGH) -- the only place in this module that
// isn't active-low, by necessity, not by choice. Inverted from rst_n here so
// the rest of the signal stays project-convention active-low.
module xadc_interface (
    input  wire logic clk,
    input  wire logic rst_n,

    // Differential analog input (VAUX0 pair, routed to xa_p[0]/xa_n[0])
    input  wire logic vauxp0,
    input  wire logic vauxn0,

    output logic [11:0] sample,
    output logic        sample_valid
);

    localparam logic [6:0] VAUX0_ADDR = 7'h10;

    // -- DRP bus to the XADC IP -----------------------------------------------
    logic [15:0] di_in;
    logic [6:0]  daddr_in;
    logic        den_in;
    logic        dwe_in;
    logic        drdy_out;
    logic [15:0] do_out;
    logic        eoc_out;

    assign di_in    = 16'h0000;
    assign dwe_in    = 1'b0;
    assign daddr_in  = VAUX0_ADDR;
    assign den_in    = eoc_out;

    xadc_wiz_0 u_xadc_wiz (
        .di_in    (di_in),
        .daddr_in (daddr_in),
        .den_in   (den_in),
        .dwe_in   (dwe_in),
        .drdy_out (drdy_out),
        .do_out   (do_out),
        .dclk_in  (clk),
        .reset_in (!rst_n),
        .vp_in    (1'b0),
        .vn_in    (1'b0),
        .vauxp0   (vauxp0),
        .vauxn0   (vauxn0),
        .user_temp_alarm_out (),
        .vccint_alarm_out    (),
        .vccaux_alarm_out    (),
        .ot_out              (),
        .channel_out         (),
        .eoc_out  (eoc_out),
        .alarm_out           (),
        .eos_out             (),
        .busy_out            ()
    );

    // -- Latch a fresh sample whenever the IP reports one ready --------------
    always_ff @(posedge clk) begin
        if (!rst_n) begin
            sample       <= 12'd0;
            sample_valid <= 1'b0;
        end
        else begin
            sample_valid <= 1'b0;
            if (drdy_out) begin
                sample       <= do_out[15:4];
                sample_valid <= 1'b1;
            end
        end
    end

endmodule
